-- Legacy entry point retained for older project references.
--
-- Do not run standalone ALTER statements after this repository adopted Flyway.
-- PostgreSQL/Supabase schema ownership now lives in:
--   backend/src/main/resources/db/migration/postgresql/V1__create_core_schema.sql
--   backend/src/main/resources/db/migration/postgresql/V2__add_integrity_constraints_and_indexes.sql
--
-- For a Hibernate-created legacy schema, run database/supabase/preflight.sql,
-- start the backend with SPRING_PROFILES_ACTIVE=postgres, then run
-- scripts/verify-supabase-schema.sh.
